spring.application.name=spring_api_restaurant_demo
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/restaurant}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

security.jwt.private-key-location=${RSA_PRIVATE_KEY_LOCATION:classpath:keys/private_key.pem}
security.jwt.public-key-location=${RSA_PUBLIC_KEY_LOCATION:classpath:keys/public_key.pem}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}

